language: php

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/php-cs-fixer fix -v
  - vendor/bin/phpunit --verbose

matrix:
  fast_finish: true
